WebEngineering/Controllers/LieferungController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebEngineering.Data;
using WebEngineering.Models;

namespace WebEngineering.Controllers
{
    [Authorize]
    public class LieferungController : Controller
    {
        private readonly IdentityContext _context;

        public LieferungController(IdentityContext context)
        {
            _context = context;
        }

        // GET: Lieferung
        public async Task<IActionResult> Index()
        {
            var identityContext = _context.Lieferungen.Include(l => l.Produkt);
            return View(await identityContext.ToListAsync());
        }

        // GET: Lieferung/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Lieferungen == null)
            {
                return NotFound();
            }

            var lieferung = await _context.Lieferungen
                .Include(l => l.Produkt)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (lieferung == null)
            {
                return NotFound();
            }

            return View(lieferung);
        }

        // GET: Lieferung/Create
        public IActionResult Create()
        {
            ViewData["ProduktId"] = new SelectList(_context.Produkte, "Id", "Name");
            return View();
        }

        // POST: Lieferung/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ProduktId,Date,Menge")] Lieferung lieferung)
        {
            if (ModelState.IsValid)
            {
                _context.Add(lieferung);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ProduktId"] = new SelectList(_context.Produkte, "Id", "Id", lieferung.ProduktId);
            return View(lieferung);
        }

        // GET: Lieferung/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Lieferungen == null)
            {
                return NotFound();
            }

            var lieferung = await _context.Lieferungen.FindAsync(id);
            if (lieferung == null)
            {
                return NotFound();
            }
            ViewData["ProduktId"] = new SelectList(_context.Produkte, "Id", "Id", lieferung.ProduktId);
            return View(lieferung);
        }

        // POST: Lieferung/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ProduktId,Date,Menge")] Lieferung lieferung)
        {
            if (id != lieferung.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(lieferung);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LieferungExists(lieferung.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ProduktId"] = new SelectList(_context.Produkte, "Id", "Id", lieferung.ProduktId);
            return View(lieferung);
        }

        // GET: Lieferung/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Lieferungen == null)
            {
                return NotFound();
            }

            var lieferung = await _context.Lieferungen
                .Include(l => l.Produkt)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (lieferung == null)
            {
                return NotFound();
            }

            return View(lieferung);
        }

        // POST: Lieferung/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Lieferungen == null)
            {
                return Problem("Entity set 'IdentityContext.Lieferungen'  is null.");
            }
            var lieferung = await _context.Lieferungen.FindAsync(id);
            if (lieferung != null)
            {
                _context.Lieferungen.Remove(lieferung);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LieferungExists(int id)
        {
          return (_context.Lieferungen?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

WebEngineering/Controllers/ProduktController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebEngineering.Data;
using WebEngineering.Models;

namespace WebEngineering.Controllers
{
    [Authorize]
    public class ProduktController : Controller
    {
        private readonly IdentityContext _context;

        public ProduktController(IdentityContext context)
        {
            _context = context;
        }

        // GET: Produkt
        public async Task<IActionResult> Index()
        {
              return _context.Produkte != null ? 
                          View(await _context.Produkte.ToListAsync()) :
                          Problem("Entity set 'IdentityContext.Produkte'  is null.");
        }


        // Inventory
        // Inventory
        public async Task<IActionResult> InventoryHistory(int produktId)
        {
            if (produktId <= 0)
            {
                return BadRequest("Ungültige Produkt-ID.");
            }

            var lieferungen = await _context.Lieferungen
                .Where(l => l.ProduktId == produktId)
                .ToListAsync();

            var bestellungen = await _context.Bestellungen
                .Where(b => b.ProduktId == produktId)
                .ToListAsync();

            var inventoryHistory = new List<Inventory>();

            int currentInventory = 0;

            foreach (var lieferung in lieferungen)
            {
                currentInventory += lieferung.Menge;
                inventoryHistory.Add(new Inventory
                {
                    Datum = lieferung.Date,
                    Lagerbestand = currentInventory
                });
            }

            foreach (var bestellung in bestellungen)
            {
                currentInventory -= bestellung.Menge;
                inventoryHistory.Add(new Inventory
                {
                    Datum = bestellung.Date,
                    Lagerbestand = currentInventory
                });
            }

            ViewBag.ProduktId = produktId;
            inventoryHistory = inventoryHistory.OrderBy(i => i.Datum).ToList();
            ViewBag.InventoryHistory = inventoryHistory;

            return View();
        }


        // Average
        public async Task<IActionResult> DurchschnittlicheMengen()
        {
            var produkte = await _context.Produkte
        .Include(p => p.Bestellungen)
        .Include(p => p.Lieferungen)
        .ToListAsync();

            var durchschnittlicheMengen = new List<Average>();

            foreach (var produkt in produkte)
            {

                var durchschnittlicheBestellmenge = produkt.Bestellungen.Any()==true
                    ? produkt.Bestellungen.Average(b => b.Menge)
                    : 0;

                var durchschnittlicheLiefermenge = produkt.Lieferungen.Any()== true
                    ? 
                     produkt.Lieferungen.Average(l => l.Menge):0;

                durchschnittlicheMengen.Add(new Average
                {
                    Id = produkt.Id,
                    Name = produkt.Name,
                    DurchschnittlicheBestellmenge = (decimal)durchschnittlicheBestellmenge,
                    DurchschnittlicheLiefermenge = (decimal)durchschnittlicheLiefermenge,
                });
            }

            ViewBag.Produkte = durchschnittlicheMengen;

            return View();
        }

        // GET: Produkt/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Produkte == null)
            {
                return NotFound();
            }

            var produkt = await _context.Produkte
                .FirstOrDefaultAsync(m => m.Id == id);
            if (produkt == null)
            {
                return NotFound();
            }

            return View(produkt);
        }

        // GET: Produkt/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Produkt/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] Produkt produkt)
        {
            if (ModelState.IsValid)
            {
                _context.Add(produkt);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(produkt);
        }

        // GET: Produkt/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Produkte == null)
            {
                return NotFound();
            }

            var produkt = await _context.Produkte.FindAsync(id);
            if (produkt == null)
            {
                return NotFound();
            }
            return View(produkt);
        }

        // POST: Produkt/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] Produkt produkt)
        {
            if (id != produkt.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(produkt);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProduktExists(produkt.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(produkt);
        }

        // GET: Produkt/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Produkte == null)
            {
                return NotFound();
            }

            var produkt = await _context.Produkte
                .FirstOrDefaultAsync(m => m.Id == id);
            if (produkt == null)
            {
                return NotFound();
            }

            return View(produkt);
        }

        // POST: Produkt/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Produkte == null)
            {
                return Problem("Entity set 'IdentityContext.Produkte'  is null.");
            }
            var produkt = await _context.Produkte.FindAsync(id);
            if (produkt != null)
            {
                _context.Produkte.Remove(produkt);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProduktExists(int id)
        {
          return (_context.Produkte?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

WebEngineering/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Lagerverwaltung</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebEngineering.styles.css" asp-append-version="true" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Lagerverwaltung</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Produkte
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" asp-area="" asp-controller="Produkt" asp-action="Create">Create Product</a></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="Produkt" asp-action="Index">Products List</a></li>
                            </ul>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Lieferungen
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" asp-area="" asp-controller="Lieferung" asp-action="Create">Create Lieferung</a></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="Lieferung" asp-action="Index">Lieferung List</a></li>
                            </ul>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Bestellungen
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" asp-area="" asp-controller="Bestellung" asp-action="Create">Create Bestellung</a></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="Bestellung" asp-action="Index">Bestellung List</a></li>
                            </ul>
                        </li>



                        



                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Lagerverwaltung - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script>
        $(document).ready(function () {
            $('.dropdown-toggle').dropdown();
        });
    </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>